config = sprintf(  ['N=%.15g' ...
' d=%.15g'          ...
' tFin=%.15g'       ...
' G=%.15g'          ...
' sampling=%.15g'   ...
' e=%.15g'          ...
' schema=%s'        ...
' nSteps=%.15g',    ...
' %s'] ,            ...
    N                  ,...
    d                  ,...
    tFin               ,...
    G                  ,...
    sampling           ,...
    e                  ,...
    schema             ,...
    nSteps             ,...
    sBody                );




%%%%%  --- SIMULATION ---   %%%%%
if (Resimulate) %test if the file exists
    %if not:
    cmd = sprintf('%s%s %s %s output=%s' , repertoire, executable, inputName,config ,name);
    system(strcat("wsl ",cmd)); % Wsl to compile using gcc on the wsl (windows subsystem for linux)
end